### ISSUE TITLE
JuliaDB setcol yields MomPool errors

### ISSUE THREAD

**Issue by MaximilianJHuber** [JuliaData/MemPool.jl#16]
I have a table:
```
Distributed Table with 169678550 rows in 34 chunks:
Columns:
#  colname  type
────────────────────────────────────────────────
1  nr     Int32
2  str    String
```

The `str` only takes 23 different values and I have a Dict that translates them into an `Int8`:
```
setcol(t, :str, :str=>c -> dictionary[c]);
```

yields:

> On worker 2:
KeyError: key "" not found

but `unique(collect(select(t, :str)))` just shows the 23 different values and `""` is not one of them. If I manually add `""` to the `Dict` with some arbitrary value I get:

> On worker 5:
ArgumentError: Reference array points beyond the end of the pool

**Comment by MaximilianJHuber** [comment]
Okay, downgrading JuliaDB to 0.8.1 alleviate the issue...

**Comment by jpsamaroo** [comment]
Closing as there is no MWE and JuliaDB is unmaintained.
