### ISSUE TITLE
Management of files

### ISSUE THREAD

**Issue by DrChainsaw** [JuliaData/MemPool.jl#36]
Maybe first question to ask is if this package is intended for people like me who only wish to use the disk as an extension of the RAM?

Anyways, it seems like the files created needs to be manually deleted (e.g. by calling pooldelete) when no longer needed, or?

If I want files to be deleted when the DRef is no longer used, is it correct to wrap the DRef in a Ref and register a finalizer for that Ref (while ofc making sure all other parts of the program only interact with the referenced data through some struct wrapping the Ref)? 

It seems to work in casual testing but I'm afraid there might be hidden pitfalls with it when let loose in the wild.

**Comment by jpsamaroo** [comment]
Automatic swap-to-disk (and deletion upon `DRef` being finalized) was implemented in https://github.com/JuliaData/MemPool.jl/pull/60. Please see the environment variables in https://github.com/JuliaData/MemPool.jl/blob/49bb60f6bced32950b329d1556eaccb797d0c16f/src/MemPool.jl#L118-L129 to get an idea of how to use it (documentation is forthcoming).
