### ISSUE TITLE
bad ccall is causing segfaulting on master

### ISSUE THREAD

**Issue by vtjnash** [JuliaData/MemPool.jl#52]
This ccall is broken on master, but is also unnecessary (since Julia v1.6) https://github.com/JuliaData/MemPool.jl/blob/f62e3ec836033d156b62627633e93be3f4b6b2e4/src/lock.jl#L28-L29

Refs https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_date/2021-06/09/FileTrees.1.7.0-DEV-f442e4230a.log

**Comment by jpsamaroo** [comment]
Should be `ccall(:jl_gc_enable_finalizers, Cvoid, (Ptr{Cvoid}, Int32,), C_NULL, on)`, probably due to https://github.com/JuliaLang/julia/pull/40715. We can pass `C_NULL` since we're disabling finalizers on our current task/thread. Thanks for the report @vtjnash !

**Comment by vtjnash** [comment]
It really probably shouldn't be there at all (and current task/thread is the only legal parameter there, so yes that must be the case)

**Comment by jpsamaroo** [comment]
Good point, now that `SpinLock` disables finalizers during `lock` calls.
